version: "3"

services:
  bot:
    image: python:3.11
    container_name: kidneyScanner-bot
    build:
      dockerfile: Dockerfile
      context: .
    command: python3 -m app --config ./config/config.yaml
    restart: always
#    env_file: .env
    environment:
      - TZ=Europe/Moscow
