version: 1
#objects:
#  queue:
#    class: queue.Queue
#    maxsize: 1000
disable_existing_loggers: false
formatters:
  simple:
    format: '[%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s'
    datefmt: '%d-%m-%Y %H:%M:%S'
  json:
    (): logs.MyJSONFormatter
    fmt_keys:
      level: levelname
      message: message
      timestamp: timestamp
      logger: name
      module: module
      function: funcName
      line: lineno
      thread_name: threadName
filters:
  no_errors:
    (): logs.NonErrorFilter

handlers:
  stderr:
    class: logging.StreamHandler
#    level: DEBUG
    formatter: simple
    stream: 'ext://sys.stderr'
  file_json:
    class: logging.handlers.RotatingFileHandler
#    level: DEBUG
    formatter: json
    filename: ../logs/imitator.jsonl
    maxBytes: 100000
    backupCount: 3
  queue_handler:
    class: logs.QueueListenerHandler
#    queue: cfg://objects.queue
    handlers:
    - cfg://handlers.file_json
#    - cfg://handlers.stderr
    respect_handler_level: true
loggers:
  root:
    level: DEBUG
    handlers:
    - stderr
    - file_json
#    - queue_handler